import { NextRequest, NextResponse } from "next/server";
// @ts-expect-error — html-to-docx has no bundled types
import HTMLtoDOCX from "html-to-docx";
import { REPORT_SECTIONS } from "@/lib/constants/reportSections";
import type { ReportSectionId, ReportSectionState } from "@/types";

function buildReportHtml(
  sections: Record<ReportSectionId, ReportSectionState>,
  title: string,
  datasetName?: string
): string {
  const now = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let html = `
    <div style="text-align: center; margin-bottom: 40px;">
      <h1 style="font-size: 28px; margin-bottom: 4px;">${title}</h1>
      ${datasetName ? `<p style="color: #666; font-size: 14px;">${datasetName}</p>` : ""}
      <p style="color: #888; font-size: 12px;">Generated on ${now} | Twimbit CX Stars</p>
      <hr style="margin-top: 20px; border: none; border-top: 2px solid #E8A045;" />
    </div>
  `;

  for (const section of REPORT_SECTIONS) {
    const content = sections[section.id];
    if (!content || !content.html || content.status === "empty") continue;

    html += `
      <h1 style="font-size: 22px; color: #1a1a1a; margin-top: 32px; margin-bottom: 12px; border-bottom: 1px solid #ddd; padding-bottom: 8px;">
        ${section.label}
      </h1>
      ${content.html}
    `;
  }

  html += `
    <div style="margin-top: 48px; padding-top: 16px; border-top: 1px solid #ddd; text-align: center;">
      <p style="color: #888; font-size: 10px;">
        This report was generated by BuddyCX — Twimbit CX Stars Benchmarking Programme
      </p>
    </div>
  `;

  return html;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    // Support both legacy (flat html) and new (reportSections) formats
    let finalHtml: string;
    let title: string;

    if (body.reportSections) {
      title = body.title || "CX Stars Report";
      finalHtml = buildReportHtml(
        body.reportSections,
        title,
        body.datasetName
      );
    } else if (body.html) {
      title = body.title || "Report";
      finalHtml = body.html;
    } else {
      return NextResponse.json(
        { error: "Either html or reportSections is required" },
        { status: 400 }
      );
    }

    const fullHtml = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <style>
      body { font-family: Arial, sans-serif; font-size: 12px; line-height: 1.6; color: #1a1a1a; }
      h1 { font-size: 22px; }
      h2 { font-size: 18px; color: #333; }
      h3 { font-size: 15px; color: #444; }
      blockquote { border-left: 3px solid #E8A045; padding-left: 12px; color: #555; font-style: italic; }
      table { border-collapse: collapse; width: 100%; }
      td, th { border: 1px solid #ddd; padding: 6px 10px; }
      th { background: #f5f5f5; font-weight: bold; }
    </style>
  </head>
  <body>${finalHtml}</body>
</html>`;

    const docxBuffer = await HTMLtoDOCX(fullHtml, null, {
      table: { row: { cantSplit: true } },
      footer: true,
      pageNumber: true,
      title,
    });

    const safeTitle = title.replace(/[^a-z0-9_\-]/gi, "_");

    return new Response(docxBuffer, {
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${safeTitle}.docx"`,
      },
    });
  } catch (error: any) {
    console.error("DOCX export error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate DOCX" },
      { status: 500 }
    );
  }
}
