import { NextRequest, NextResponse } from "next/server";
import puppeteer from "puppeteer";
import { REPORT_SECTIONS } from "@/lib/constants/reportSections";
import type { ReportSectionId, ReportSectionState } from "@/types";

function buildPdfHtml(
  sections: Record<ReportSectionId, ReportSectionState>,
  title: string,
  datasetName?: string
): string {
  const now = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let sectionsHtml = "";

  for (const section of REPORT_SECTIONS) {
    const content = sections[section.id];
    if (!content || !content.html || content.status === "empty") continue;

    sectionsHtml += `
      <section class="report-section">
        <h1 class="section-title">${section.label}</h1>
        <div class="section-content">${content.html}</div>
      </section>
    `;
  }

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    @page {
      size: A4;
      margin: 2.5cm 2cm;
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.65;
      color: #1a1a1a;
    }

    /* Cover / Header */
    .report-header {
      text-align: center;
      padding-bottom: 32px;
      margin-bottom: 32px;
      border-bottom: 3px solid #E8A045;
    }
    .report-header h1 {
      font-size: 28pt;
      font-weight: 700;
      color: #0C0E14;
      margin-bottom: 4px;
    }
    .report-header .subtitle {
      font-size: 12pt;
      color: #555;
      margin-bottom: 2px;
    }
    .report-header .meta {
      font-size: 9pt;
      color: #888;
    }

    /* Sections */
    .report-section {
      page-break-inside: avoid;
      margin-bottom: 28px;
    }
    .section-title {
      font-size: 18pt;
      font-weight: 700;
      color: #0C0E14;
      padding-bottom: 6px;
      margin-bottom: 14px;
      border-bottom: 1px solid #ddd;
    }
    .section-content h2 {
      font-size: 14pt;
      font-weight: 600;
      color: #222;
      margin: 16px 0 8px;
    }
    .section-content h3 {
      font-size: 12pt;
      font-weight: 600;
      color: #333;
      margin: 12px 0 6px;
    }
    .section-content p {
      margin: 6px 0;
    }
    .section-content ul, .section-content ol {
      padding-left: 24px;
      margin: 8px 0;
    }
    .section-content li {
      margin: 3px 0;
    }
    .section-content blockquote {
      border-left: 3px solid #E8A045;
      padding-left: 14px;
      margin: 10px 0;
      color: #555;
      font-style: italic;
    }
    .section-content strong {
      font-weight: 600;
    }
    .section-content table {
      border-collapse: collapse;
      width: 100%;
      margin: 10px 0;
    }
    .section-content td, .section-content th {
      border: 1px solid #ddd;
      padding: 6px 10px;
      font-size: 10pt;
    }
    .section-content th {
      background: #f5f5f5;
      font-weight: 600;
    }

    /* Footer */
    .report-footer {
      margin-top: 40px;
      padding-top: 14px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 8pt;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="report-header">
    <h1>${title}</h1>
    ${datasetName ? `<p class="subtitle">${datasetName}</p>` : ""}
    <p class="meta">Generated on ${now} | Twimbit CX Stars Benchmarking Programme</p>
  </div>

  ${sectionsHtml}

  <div class="report-footer">
    <p>This report was generated by BuddyCX — Twimbit CX Stars Benchmarking Programme</p>
  </div>
</body>
</html>`;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const {
      reportSections,
      title = "CX Stars Report",
      datasetName,
    }: {
      reportSections: Record<ReportSectionId, ReportSectionState>;
      title?: string;
      datasetName?: string;
    } = body;

    if (!reportSections) {
      return NextResponse.json(
        { error: "reportSections is required" },
        { status: 400 }
      );
    }

    const html = buildPdfHtml(reportSections, title, datasetName);

    // Launch headless browser
    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "2.5cm",
        right: "2cm",
        bottom: "2.5cm",
        left: "2cm",
      },
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="width: 100%; font-size: 8px; color: #999; padding: 0 2cm; display: flex; justify-content: space-between;">
          <span>${title}</span>
          <span>Twimbit CX Stars</span>
        </div>
      `,
      footerTemplate: `
        <div style="width: 100%; font-size: 8px; color: #999; padding: 0 2cm; display: flex; justify-content: space-between;">
          <span>BuddyCX Report</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `,
    });

    await browser.close();

    const safeTitle = title.replace(/[^a-z0-9_\-]/gi, "_");

    return new Response(Buffer.from(pdfBuffer), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${safeTitle}.pdf"`,
      },
    });
  } catch (error: any) {
    console.error("PDF export error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate PDF" },
      { status: 500 }
    );
  }
}
