import Anthropic from "@anthropic-ai/sdk";
import * as fs from "fs";
import * as path from "path";

const SKILLS = [
  "cx-data-query",
  "cx-insight-synthesis",
  "cx-report-drafting",
  "cx-linkedin",
];

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });

function collectFiles(dir: string, prefix: string = ""): Array<[string, Buffer]> {
  const files: Array<[string, Buffer]> = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      files.push(...collectFiles(fullPath, relativePath));
    } else {
      files.push([relativePath, fs.readFileSync(fullPath)]);
    }
  }
  return files;
}

async function uploadSkill(skillName: string): Promise<string> {
  const skillDir = path.join(process.cwd(), "skills", skillName);

  if (!fs.existsSync(skillDir)) {
    throw new Error(`Skill directory not found: ${skillDir}`);
  }

  const files = collectFiles(skillDir);
  const fileEntries = files.map(([name, content]) => {
    const filePath = `${skillName}/${name}`;
    return [filePath, new Blob([content])] as [string, Blob];
  });

  console.log(`Uploading ${skillName} (${files.length} files)...`);

  // Use the Anthropic SDK beta skills endpoint
  const skill = await (anthropic as any).beta.skills.create({
    display_title: skillName,
    files: fileEntries,
    betas: ["skills-2025-10-02"],
  });

  console.log(`  Created: ${skill.id} (version: ${skill.latest_version})`);
  return skill.id;
}

async function main() {
  console.log("Uploading skills to Anthropic API...\n");

  const ids: Record<string, string> = {};

  for (const skill of SKILLS) {
    try {
      ids[skill] = await uploadSkill(skill);
    } catch (error) {
      console.error(`  Failed to upload ${skill}:`, error);
      process.exit(1);
    }
  }

  // Append skill IDs to .env.local
  const envPath = path.join(process.cwd(), ".env.local");
  const envLines = [
    "",
    "# Agent Skill IDs (auto-generated by scripts/upload-skills.ts)",
    `SKILL_ID_CX_DATA_QUERY=${ids["cx-data-query"]}`,
    `SKILL_ID_CX_INSIGHT_SYNTHESIS=${ids["cx-insight-synthesis"]}`,
    `SKILL_ID_CX_REPORT_DRAFTING=${ids["cx-report-drafting"]}`,
    `SKILL_ID_CX_LINKEDIN=${ids["cx-linkedin"]}`,
    "",
  ];

  fs.appendFileSync(envPath, envLines.join("\n"));
  console.log("\nSkill IDs written to .env.local");
  console.log("\nDone!");
}

main().catch(console.error);
